name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc

          - os: macos-latest
            target: x86_64-apple-darwin

          - os: macos-latest
            target: aarch64-apple-darwin

          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Add target
        run: rustup target add ${{ matrix.target }}

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      # 可选：减小体积（Linux/mac 生效）
      - name: Strip binary
        shell: bash
        run: |
          BIN="renord"
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            BIN="renord.exe"
          fi

          strip target/${{ matrix.target }}/release/$BIN || true

      - name: Package
        shell: bash
        run: |
          BIN="renord"
          EXT="tar.gz"

          if [[ "${{ runner.os }}" == "Windows" ]]; then
            BIN="renord.exe"
            EXT="zip"
          fi

          OUT="renord-${{ matrix.target }}.$EXT"

          mkdir dist
          cp target/${{ matrix.target }}/release/$BIN dist/

          if [[ "$EXT" == "zip" ]]; then
            cd dist
            7z a ../$OUT $BIN
          else
            tar -czf $OUT -C dist $BIN
          fi

      - name: Checksum
        shell: bash
        run: |
          sha256sum renord-${{ matrix.target }}.* > renord-${{ matrix.target }}.sha256

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            renord-${{ matrix.target }}.*